version: "3.8"

services:
  app:
    image: space365/candembackend:api  # Matches the image pushed to Docker Hub
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    networks:
      - bank_network

networks:
  bank_network:
    driver: bridge
