name: Deploy Backend to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.KEY }}
          port: 22
          script: |
            # Create and navigate to the project directory
            mkdir -p /home/ec2-user/bank_api_project
            cd /home/ec2-user/bank_api_project

            # Set Git credentials using the PAT
            git config --global url."https://x-access-token:${{secrets.Token }}@github.com/".insteadOf "https://github.com/"

            # Check if it's a Git repository, pull or clone using HTTPS
            if [ -d ".git" ]; then
              git pull origin main
            else
              git clone https://github.com/Space365X/candembackend.git .
            fi

            # Set environment variables
            export MONGO_URI=${{ secrets.MONGO_URI }}
            export JWT_SECRET=${{ secrets.JWT_SECRET }}
            export REDIS_HOST=${{ secrets.REDIS_HOST }}
            export REDIS_PORT=${{ secrets.REDIS_PORT }}
            # Add if required

            # Build and run Docker Compose with error checking
            if [ -f "docker-compose.yml" ]; then
              docker-compose build
              docker-compose up -d
            else
              echo "Error: docker-compose.yml not found!"
              exit 1
            fi

            # Restart NGINX
            sudo systemctl restart nginx
